language: go

go:
    - "1.9"

install:
    - go get -u github.com/kardianos/govendor
    - govendor sync

notifications:
    email: false    
env:   
CGO_ENABLED=1
CGO_CFLAGS= -g -O2
CGO_CXXFLAGS= -g -O2
CGO_FFLAGS= -g -O2
CGO_LDFLAGS= -g -O2
